import 'package:json_annotation/json_annotation.dart';

part 'bot_settings_response.g.dart'; // Generated file

@JsonSerializable()
class BotSettingsResponse {

  String botMainColor;

  BotSettingsResponse(this.botMainColor);

  Map<String, dynamic> toJson() => _$BotSettingsResponseToJson(this);

  // Added factory constructor and fromJson method generated by json_serializable
  factory BotSettingsResponse.fromJson(Map<String, dynamic> json) =>
      _$BotSettingsResponseFromJson(json);
}
